version: '3'
services:
  nest_video_backup:
    container_name: nest_video_backup
    restart: unless-stopped
    user: 1000:1000 # optional, but recommended if you don't want permissions to be root
    build: .
    volumes:
      - /path/to/your/storage:/videos
      - /path/to/folder/with/ini:/config
